#!/bin/bash/php
echo '+--------------------------------------------------+'
echo '| Installing Software...                           |'
echo '+--------------------------------------------------+'
echo '1) Downloading composer'
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
echo '2) Installing PHP Composer...'
php composer install
echo 'Installation ended successfully'
echo '+--------------------------------------------------+'
echo '| Installation ended successfully                  |'
echo '+--------------------------------------------------+'
echo 'Select the type of platform you want to install'
type_platform=$typePlatform
read -ep '(default: development): ' typePlatform;
php  /var/www/html/bitelnoticias/install-config.php -f=$typePlatform
# php -r "$file = file_get_contents('index.php');"
# echo $typePlatform
echo '+--------------------------------------------------+'
# 
# type_platform=$typePlatform
# echo $type_platform;
# eval "`echo 'NL=qsq' | tr 'qs' '\047\012'`"; # newline
# echo DB_NAME; read DB_NAME;

# db_name_esc=${db_name_esc//\\/\\\\\\\\}   # escape backslash
# db_name_esc=${db_name_esc//\'/\\\\\'}     # escape single quote
# db_name_esc=${db_name_esc//\"/\\\"}       # escape double quote
# db_name_esc=${db_name_esc//&/\\&}         # escape & special to sed
# db_name_esc=${db_name_esc//\//\\\/}       # escape / special to s///
# db_name_esc=${db_name_esc//${NL}/\\${NL}} # esc literal newline for sed

# and then plug in your variables properly escaped for both PHP+sed
# sed -e "s/\\(define('TYPE_PLATFORM',\\).*/\\1 '$type_platform');/" "index.php"
