#!/bin/bash/php
echo '+--------------------------------------------------+'
echo '| Installing Software...                           |'
echo '+--------------------------------------------------+'
echo '| 1) Downloading composer...                       |'
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
echo '| 2) Installing PHP Composer...                    |'
php composer install
echo '|                                                  |'
echo '+--------------------------------------------------+'
echo '| Installation ended successfully                  |'
echo '+--------------------------------------------------+'
echo '| Select the type of platform you want to install  |'
echo '| between (dev | prod)                             |'
type_platform=$typePlatform
read -ep '| (default: dev): ' typePlatform;
echo '| System creating your new platform. Please wait   |'
php  /var/www/html/bitelnoticias/install-config.php -p=$typePlatform
echo '| Loading platform....                             |'
echo '|                                                  |'
echo '| Platform install ended successfully              |'
echo '+--------------------------------------------------+'